LOCAL_PATH := $(call my-dir)

LOCAL_LIB_FILE_PATH_PREFIX := $(LOCAL_PATH)/../../../../../commonlib/src/main/jni/ffmpeg

include $(CLEAR_VARS)
LOCAL_MODULE := libavcodec-58
LOCAL_SRC_FILES := $(LOCAL_LIB_FILE_PATH_PREFIX)/$(TARGET_ARCH_ABI)/$(LOCAL_MODULE).so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_LIB_FILE_PATH_PREFIX)/include
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavformat-58
LOCAL_SRC_FILES := $(LOCAL_LIB_FILE_PATH_PREFIX)/$(TARGET_ARCH_ABI)/$(LOCAL_MODULE).so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_LIB_FILE_PATH_PREFIX)/include
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavutil-56
LOCAL_SRC_FILES := $(LOCAL_LIB_FILE_PATH_PREFIX)/$(TARGET_ARCH_ABI)/$(LOCAL_MODULE).so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_LIB_FILE_PATH_PREFIX)/include
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libswresample-3
LOCAL_SRC_FILES := $(LOCAL_LIB_FILE_PATH_PREFIX)/$(TARGET_ARCH_ABI)/$(LOCAL_MODULE).so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_LIB_FILE_PATH_PREFIX)/include
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libswscale-5
LOCAL_SRC_FILES := $(LOCAL_LIB_FILE_PATH_PREFIX)/$(TARGET_ARCH_ABI)/$(LOCAL_MODULE).so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_LIB_FILE_PATH_PREFIX)/include
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavfilter-7
LOCAL_SRC_FILES := $(LOCAL_LIB_FILE_PATH_PREFIX)/$(TARGET_ARCH_ABI)/$(LOCAL_MODULE).so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_LIB_FILE_PATH_PREFIX)/include
include $(PREBUILT_SHARED_LIBRARY)

LOCAL_PATH:= $(call my-dir)
